# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a763d3e1b77ddba2af57b9fcc9000df6a166d73cb77617c92c69dbb06ebc38653580062d750abd95927521013a98a8ae73f9f44cfba68a293dc0312d5ab4195b

test:
  secret_key_base: c39653cca7c5f2dbff8147d1c595e47529e56a135c4c02cdc9cd66cab6647f257f12ad35c578ae5183e58a8efd81fd428de9dd4c90205acf8dde50ea81310fff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
